#!/usr/bin/env ruby

# put the session in bashrc `export AOC_SESSION="..."`
# You can find this in your browser's cookies

require 'date'
require 'erb'
require 'fileutils'

day_i = Date.today.day
day = "day#{day_i}"

script_path = "./ruby/#{day}/app.rb"
input_path = "./inputs/#{day}" 

FileUtils.mkdir_p(File.dirname(input_path))
FileUtils.mkdir_p(File.dirname(script_path))

# make the app.rb
unless File.exists?(script_path)
  puts "> render script"
  File.write(script_path, ERB.new(DATA.read).result(binding))
end

unless File.exists?(input_path)
  cmd = <<~CMD
  curl --silent --show-error --cookie "session=$AOC_SESSION" --output "#{input_path}" "https://adventofcode.com/2020/day/#{day_i}/input"
  CMD
  system(cmd)
end

# open vim
exec("vim -O #{script_path} #{input_path}")

__END__
#!/usr/bin/env ruby

# <%= day %> solution
input_file_path = File.expand_path("../../../inputs/<%= day %>", __FILE__)
lines = File.readlines(input_file_path).map(&:strip)

# your solution

